const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const FALLBACK=[{id:1,type:'piesa',title:'Far dreapta BMW Seria 3 E90',price:450,condition:'Second-hand',make:'BMW',model:'Seria 3',year:'2008',county:'Cluj',category:'Iluminare',oem:'E90-63117161678',delivery:true,description:'Far original, verificat, stare bună.'},{id:2,type:'piesa',title:'Motor 1.5 dCi Dacia Logan',price:3200,condition:'Second-hand',make:'Dacia',model:'Logan',year:'2012',county:'București',category:'Motor',oem:'K9K',delivery:true,description:'Motor complet, verificat.'},{id:3,type:'piesa',title:'Jante aliaj Audi 18 inch',price:2000,condition:'Second-hand',make:'Audi',model:'A4',year:'2017',county:'Cluj',category:'Roți',delivery:true,description:'Set 4 bucăți.'},{id:4,type:'piesa',title:'Alternator BMW 320d',price:750,condition:'Nouă',make:'BMW',model:'Seria 3',year:'2010',county:'Brașov',category:'Electrică',delivery:true,description:'Piesă nouă.'},{id:5,type:'dezmembrari',title:'Dezmembrez BMW Seria 3 E90 320d',price:0,condition:'Second-hand',make:'BMW',model:'Seria 3',year:'2008',county:'Cluj',category:'Dezmembrări',delivery:true,description:'Motor, cutie, caroserie și interior disponibile.'},{id:6,type:'piesa',title:'Cutie viteze VW Golf 6',price:1850,condition:'Second-hand',make:'Volkswagen',model:'Golf',year:'2010',county:'Iași',category:'Transmisie',delivery:true,description:'Cutie manuală, verificată.'}];
let listings=[...FALLBACK],currentUser=null,favorites=JSON.parse(localStorage.getItem('autopiese_fav')||'[]');
function toast(m){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.add('hidden'),2400)}
function money(n){return Number(n)>0?new Intl.NumberFormat('ro-RO').format(n)+' lei':'La cerere'}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'A apărut o eroare.');return d}
function route(){let h=location.hash.replace(/^#\/?/,'')||'home';const map={home:'page-home',rezultate:'page-results',menu:'page-menu',cont:'page-account',cerere:'page-request',vinde:'page-sell',dezmembrari:'page-dism',servicii:'page-services',admin:'page-admin'};$$('.page').forEach(p=>p.classList.toggle('active',p.id===map[h]));if(h==='menu')renderMenu();if(h==='cont')renderAccount();if(h==='rezultate')renderResults();if(h==='admin')loadAdmin();window.scrollTo(0,0)}
function go(x){location.hash='#/'+x}
function renderMenu(){if(currentUser){$('#menuAccountText').textContent=currentUser.name||'Contul meu';$('#adminMenu').classList.toggle('hidden',currentUser.role!=='admin')}else{$('#menuAccountText').textContent='Intră în cont';$('#adminMenu').classList.add('hidden')}}
function requireUser(next){if(currentUser){go(next);return}$('#authModal').classList.remove('hidden');window.__afterAuth=next}
function openSearch(q){$('#searchInput').value=q||$('#searchInput').value;go('rezultate');}
function renderResults(){const q=($('#resultsSearch')?.value||$('#searchInput')?.value||'').trim();$('#resultsTitle').textContent=q?`Rezultate pentru „${q}”`:'Piese auto';const query=q.toLowerCase();let data=listings.filter(x=>!query||[x.title,x.oem,x.make,x.model,x.category].join(' ').toLowerCase().includes(query));const fc=$('#filterCategory').value,fm=$('#filterMake').value,fl=$('#filterModel').value,co=$('#filterCondition').value,county=$('#filterCounty').value,max=Number($('#maxPrice').value||0);if(fc)data=data.filter(x=>x.category===fc);if(fm)data=data.filter(x=>x.make===fm);if(fl)data=data.filter(x=>x.model===fl);if(co)data=data.filter(x=>x.condition===co);if(county)data=data.filter(x=>x.county===county);if(max)data=data.filter(x=>Number(x.price||0)<=max||!x.price);if($('#withDelivery').checked)data=data.filter(x=>x.delivery);const s=$('#sortListings').value;if(s==='price_asc')data.sort((a,b)=>(a.price||0)-(b.price||0));if(s==='price_desc')data.sort((a,b)=>(b.price||0)-(a.price||0));$('#resultCount').textContent=`Am găsit ${data.length} ${data.length===1?'rezultat':'rezultate'}.`;$('#listingGrid').innerHTML=data.map(card).join('');$('#noResults').classList.toggle('hidden',data.length!==0)}
function card(x){return `<article class="listing" data-id="${x.id}"><div class="listing-top"><h3>${esc(x.title)}</h3><span class="condition">${esc(x.condition||'Second-hand')}</span></div><p>${esc([x.make,x.model,x.year].filter(Boolean).join(' · ')||'Piesă auto')}<br>${esc(x.description||'')}</p><div class="listing-bottom"><div><div class="listing-price">${money(x.price)}</div><div class="listing-location">${esc(x.county||'România')}${x.delivery?' · Livrare':''}</div></div><span>›</span></div></article>`}
function openDetail(x){$('#detailContent').innerHTML=`<div class="eyebrow">${x.type==='dezmembrari'?'DEZMEMBRĂRI':'PIESĂ AUTO'}</div><h2>${esc(x.title)}</h2><div class="two"><div class="info-card"><small>Preț</small><h3>${money(x.price)}</h3></div><div class="info-card"><small>Locație</small><h3>${esc(x.county||'România')}</h3></div></div><p>${esc(x.description||'')}</p><p><b>Compatibilitate:</b> ${esc([x.make,x.model,x.year].filter(Boolean).join(' · ')||'Vezi detaliile cu vânzătorul')}</p><p><b>Cod OEM:</b> ${esc(x.oem||'—')}</p><button class="btn primary full" onclick="toast('Contactarea vânzătorului va fi disponibilă prin mesageria internă.')">Contactează vânzătorul</button>`;$('#detailModal').classList.remove('hidden')}
async function loadCatalog(){try{const r=await api('/api/catalog/makes');$('#filterMake').innerHTML='<option value="">Toate mărcile</option>'+(r.makes||[]).map(x=>`<option>${esc(x.name)}</option>`).join('')}catch{[...new Set(listings.map(x=>x.make).filter(Boolean))].forEach(x=>$('#filterMake').insertAdjacentHTML('beforeend',`<option>${esc(x)}</option>`))}}
async function loadUser(){try{const r=await api('/api/me');currentUser=r.user||null}catch{currentUser=null}if($('#favCount'))$('#favCount').textContent=favorites.length}
function renderAccount(){if(!currentUser){requireUser('cont');return}$('#accountHello').textContent=`Salut, ${currentUser.name||'utilizator'}!`}
function accountAction(a){if(a==='listings'){go('rezultate');setTimeout(()=>{$('#resultsTitle').textContent='Anunțurile mele';const mine=listings.filter(x=>String(x.user_id)===String(currentUser?.id));$('#listingGrid').innerHTML=mine.map(card).join('');$('#resultCount').textContent=`${mine.length} anunțuri`;},0);return}if(a==='favorites'){go('rezultate');setTimeout(()=>{const f=listings.filter(x=>favorites.includes(x.id));$('#resultsTitle').textContent='Favorite';$('#listingGrid').innerHTML=f.map(card).join('');$('#resultCount').textContent=`${f.length} favorite`},0);return}if(a==='requests'){go('cerere');return}toast('Această secțiune este pregătită pentru următoarea etapă.')}
async function submitRequest(e){e.preventDefault();if(!currentUser){requireUser('cerere');return}try{await api('/api/requests',{method:'POST',body:JSON.stringify({title:$('#reqTitle').value,make:$('#reqMake').value,model:$('#reqModel').value,year:$('#reqYear').value,description:$('#reqDescription').value})});$('#requestMessage').textContent='Cererea a fost trimisă.';e.target.reset()}catch(err){$('#requestMessage').textContent=err.message}}
async function submitSell(e){e.preventDefault();if(!currentUser){requireUser('vinde');return}try{await api('/api/listings',{method:'POST',body:JSON.stringify({type:'piesa',title:$('#sellTitle').value,price:$('#sellPrice').value,condition:$('#sellCondition').value,make:$('#sellMake').value,model:$('#sellModel').value,year:$('#sellYear').value,oem:$('#sellOem').value,county:$('#sellCounty').value,description:$('#sellDescription').value,delivery:$('#sellDelivery').checked})});$('#sellMessage').textContent='Anunțul a fost trimis pentru verificare.';e.target.reset()}catch(err){$('#sellMessage').textContent=err.message}}
async function login(e){e.preventDefault();try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#loginEmail').value,password:$('#loginPassword').value})});currentUser=r.user;$('#authModal').classList.add('hidden');toast('Te-ai autentificat.');const next=window.__afterAuth||'cont';window.__afterAuth=null;go(next)}catch(err){$('#loginMessage').textContent=err.message}}
async function register(e){e.preventDefault();try{const r=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('#regName').value,email:$('#regEmail').value,phone:$('#regPhone').value,password:$('#regPassword').value})});currentUser=r.user;$('#authModal').classList.add('hidden');toast('Cont creat.');go(window.__afterAuth||'cont');window.__afterAuth=null}catch(err){$('#registerMessage').textContent=err.message}}
async function logout(){try{await api('/api/auth/logout',{method:'POST'})}catch{}currentUser=null;go('home');toast('Ai ieșit din cont.')}
async function loadAdmin(){if(!currentUser||currentUser.role!=='admin'){go('menu');toast('Zona de administrare este disponibilă doar administratorului.');return}try{const r=await api('/api/admin/overview');const s=r.stats;$('#adminContent').innerHTML=`<div class="two"><div class="info-card"><b>Utilizatori</b><h3>${s.users}</h3></div><div class="info-card"><b>Anunțuri</b><h3>${s.listings}</h3></div><div class="info-card"><b>În așteptare</b><h3>${s.pending}</h3></div><div class="info-card"><b>Cereri</b><h3>${s.requests}</h3></div></div>`}catch(e){$('#adminContent').innerHTML=`<p>${esc(e.message)}</p>`}}
$('#menuBtn').onclick=()=>go('menu');$('#closeMenu').onclick=()=>go('home');$$('[data-back]').forEach(b=>b.onclick=()=>history.back());$('#searchBtn').onclick=()=>openSearch();$('#searchInput').onkeydown=e=>{if(e.key==='Enter')openSearch()};$('#resultsSearchBtn').onclick=()=>{$('#searchInput').value=$('#resultsSearch').value;renderResults()};$('#resultsSearch').onkeydown=e=>{if(e.key==='Enter'){$('#searchInput').value=e.target.value;renderResults()}};$('#filterToggle').onclick=()=>$('#filters').classList.toggle('open');['filterCategory','filterMake','filterModel','filterCondition','filterCounty','maxPrice','withDelivery','sortListings'].forEach(id=>$('#'+id).addEventListener('change',renderResults));$('#clearFilters').onclick=()=>{['filterCategory','filterMake','filterModel','filterCondition','filterCounty'].forEach(id=>$('#'+id).value='');$('#maxPrice').value='';$('#withDelivery').checked=false;renderResults()};$('#listingGrid').onclick=e=>{const a=e.target.closest('.listing');if(a)openDetail(listings.find(x=>String(x.id)===a.dataset.id))};$('#homeRequestBtn').onclick=()=>requireUser('cerere');$('#homeDismBtn').onclick=()=>go('dezmembrari');$('#logoutBtn').onclick=logout;$('#requestForm').onsubmit=submitRequest;$('#sellForm').onsubmit=submitSell;$('#loginForm').onsubmit=login;$('#registerForm').onsubmit=register;$('#showRegister').onclick=()=>{$('#loginForm').classList.add('hidden');$('#registerForm').classList.remove('hidden')};$('#showLogin').onclick=()=>{$('#registerForm').classList.add('hidden');$('#loginForm').classList.remove('hidden')};$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));$('#favoritesBtn').onclick=()=>{go('rezultate');setTimeout(()=>{$('#resultsTitle').textContent='Favorite';const f=listings.filter(x=>favorites.includes(x.id));$('#listingGrid').innerHTML=f.map(card).join('');$('#resultCount').textContent=`${f.length} favorite`},0)};$('#cartBtn').onclick=()=>toast('Coșul va fi activ când vom introduce comenzile online.');$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='account')currentUser?go('cont'):requireUser('cont');else if(a==='request')requireUser('cerere');else if(a==='sell')requireUser('vinde');else if(a==='dism')go('dezmembrari');else if(a==='services')go('servicii');else if(a==='admin')go('admin');else toast('Această secțiune va fi conectată în etapa următoare.')});$$('[data-account]').forEach(b=>b.onclick=()=>accountAction(b.dataset.account));$$('[data-search-dism]').forEach(b=>b.onclick=()=>openSearch(b.dataset.searchDism));
window.addEventListener('hashchange',route);(async()=>{await loadUser();await loadCatalog();route()})();
